
services:

  analogic:
    build: .
    environment:
      - ANALOGIC_LOAD_SAMPLE_APPS=True

  apache:
    image: 'bitnami/apache:latest'
    user: root
    ports:
      - '8080:8080'
    environment:
      - APACHE_HTTP_PORT_NUMBER=8080
    volumes:
      - ./apache-proxy.conf:/opt/bitnami/apache/conf/vhosts/00_status-vhost.conf
