version: 2.1

jobs:
  run-unit-tests:

    docker:
      - image: cimg/python:3.10.1
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt

      - run:
          name: run tests
          command: python -m unittest analogic\tests\test_setting.py

workflows:
  say-hello-workflow:
    jobs:
      - run-unit-tests
