# This is a basic workflow to help you get started with Actions

name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
        
      - name: Run Unit tests
        run: python -m unittest analogic/tests/test_setting.py
        
      - name: Start containers
        run: docker-compose -f docker-compose-flask.yml up -d --build
        
      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/helloanalogic_base.cy.js
          wait-on: "http://localhost:5000"
          browser: chrome
          headless: true
        
      - name: Stop containers
        if: always()
        run: docker-compose -f docker-compose-flask.yml down

